### ISSUE TITLE
Where is parent POM?

### ISSUE THREAD

**Issue by AIMMOTH** [GoogleCloudPlatform/getting-started-java#171]
"Getting started" examples uses a parent pom, where is it?

https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/pom.xml#L25

**Comment by tswast** [comment]
The parent pom is provided by this project https://github.com/GoogleCloudPlatform/java-repo-tools That said, you should be able to safely remove the parent definition and have the sample still work. If it doesn't, that's definitely a bug.

Closing, since hopefully I answered your question but feel free to reopen.
