### ISSUE TITLE
Cannot run the local devserver for helloworld-gae-javasdk-tools

### ISSUE THREAD

**Issue by kdunn926** [GoogleCloudPlatform/getting-started-java#946]
Hello,

I tried to follow the steps in the readme (`mvn clean appengine:devserver`) and I saw this error:
```
[ERROR] Could not find goal 'devserver' in plugin com.google.cloud.tools:appengine-maven-plugin:2.3.0 among
 available goals cloudSdkLogin, deploy, deployAll, deployCron, deployDispatch, deployDos, deployIndex, 
deployQueue, genRepoInfoFile, help, run, stage, start, stop -> [Help 1]
```

If I use `appengine:run` I get this error:
```
appengine:run is only available for appengine-web.xml based projects
```

**Comment by lesv** [comment]
Which sample are you using?

**Comment by kdunn926** [comment]
I'm trying to model some existing code from the helloworld-gae-javasdk-tools example.

**Comment by averikitsch** [comment]
That example is using the deprecated App Engine SDK based plugin, `com.google.appengine:appengine-maven-plugin`. However, the README was updated to use the recommended [Cloud based SDK](https://cloud.google.com/appengine/docs/standard/java/maven-reference), `com.google.cloud.tools:appengine-maven-plugin`. The new command would be `mvn appengine:start`.

**Comment by kdunn926** [comment]
@averikitsch  - when I use `mvn appengine:start` I get the following error (same as `mvn appengine:run`:
```
appengine:run is only available for appengine-web.xml based projects
```

What options exist to run a YAML-based configuration?

**Comment by averikitsch** [comment]
Sorry @kdunn926, I misspoke. Please ensure you have the following:
* [`src/main/webapp/WEB-INF/appengine-web.xml`](https://cloud.google.com/appengine/docs/standard/java/config/appref)
* You are using Java 8 locally
* And have packaged the app: `mvn package appengine:run`

If you want to use [`app.yaml`](https://cloud.google.com/appengine/docs/standard/java11/config/appref) from your root directory, you must upgrade to Java 11. Learn more [here](https://cloud.google.com/appengine/docs/standard/java11/building-app/writing-web-service#creating_the_appyaml_file). With the Java 11 runtime, you must provide your own server for example Spring Boot with Jetty or Tomcat. The `appengine:run` goal does not work for `app.yaml` based projects because each server has a different start up command ie `spring-boot:run` for Spring Boot.
